# Generated by Django 6.0.3 on 2026-03-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(max_length=100)),
                ('variable_changed', models.CharField(max_length=100)),
                ('old_value', models.FloatField()),
                ('new_value', models.FloatField()),
                ('predicted_health', models.FloatField()),
                ('predicted_stress', models.FloatField()),
                ('predicted_income', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twin.digitaltwin')),
            ],
        ),
    ]
