# Generated by Django 6.0.3 on 2026-03-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(choices=[('sleep', 'Sleep Optimization'), ('fitness', 'Fitness Boost'), ('stress', 'Stress Reduction'), ('custom', 'Custom Simulation')], default='custom', max_length=20)),
                ('sleep_hours', models.FloatField()),
                ('exercise_days', models.IntegerField()),
                ('water_intake', models.IntegerField()),
                ('stress_level', models.FloatField()),
                ('screen_time', models.FloatField()),
                ('predicted_health', models.FloatField(help_text='0–100')),
                ('predicted_stress', models.FloatField(help_text='0–10')),
                ('predicted_energy', models.FloatField(help_text='0–100')),
                ('predicted_longevity', models.FloatField(help_text='0–100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='twin.digitaltwin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
