# Generated by Django 6.0.3 on 2026-03-08 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('height', models.FloatField(default=170.0, help_text='cm')),
                ('weight', models.FloatField(default=70.0, help_text='kg')),
                ('sleep_hours', models.FloatField(default=7.0, help_text='hours per night')),
                ('exercise_days', models.IntegerField(default=3, help_text='days per week')),
                ('water_intake', models.IntegerField(default=6, help_text='glasses per day')),
                ('stress_level', models.FloatField(default=5.0, help_text='1–10 scale')),
                ('screen_time', models.FloatField(default=6.0, help_text='hours per day')),
                ('diet', models.CharField(choices=[('balanced', 'Balanced'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('other', 'Other')], default='balanced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
